[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    adafruit/Adafruit Fingerprint Sensor Library
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306

build_flags =
    -D PIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH